### ISSUE TITLE
Downloading subtitles fails on android tv's

### ISSUE THREAD

**Issue by felipejfc** [scakemyer/quasar#13]
It has something to do with the temporary folder we are downloading the subs, by default there is no write permissions on this folder, one possible solution is to write to app's temp folder, not to system's one.

**Comment by scakemyer** [comment]
Sounds like a good solution to avoid this problem. It's the only thing in the codebase that is using `ioutil.TempFile` [here](https://github.com/scakemyer/quasar/blob/master/api/subtitles.go#L195) so it would make sense to avoid it.

**Comment by gpiano** [comment]
I have the same issue. What's the proper fix in the source? Thanks!

**Comment by felipejfc** [comment]
I took a look into opensubtitle's plugin and they do this way:

```
__profile__    = xbmc.translatePath( __addon__.getAddonInfo('profile') ).decode("utf-8")
__temp__       = xbmc.translatePath( os.path.join( __profile__, 'temp', '') ).decode("utf-8")

...
...

if xbmcvfs.exists(__temp__):
  shutil.rmtree(__temp__)
xbmcvfs.mkdirs(__temp__)


...
...

subtitle = os.path.join(__temp__, "%s.%s" %(str(uuid.uuid4()), format))

```

I think that this would work... However I have no time atm to make a PR cause of work. Maybe I'll do it on saturday if no one do it first.

**Comment by scakemyer** [comment]
Except in our case it's in Golang, not Python ;)

**Comment by felipejfc** [comment]
Sure, but this snippet is very simple to translate to go :)

**Comment by i96751414** [comment]
@scakemyer Great work man! A few days ago you've asked me something.. I'm trying to find the issue but no luck... Can you help? :p

**Comment by scakemyer** [comment]
Uh library related stuff, somewhere ;)

**Comment by gpiano** [comment]
Any idea when we are going to have a release with this fix? Thanks!
