### ISSUE TITLE
Need help building daemon

### ISSUE THREAD

**Issue by KindKitty** [scakemyer/quasar#17]
Hi, I'm trying to build the daemon and hope to figure out what I'm doing wrong. 
I just wanted to make quasar add episodes to my library only one day after its air date, it's a pretty specific change but also easy to do so I tried to build the one line change myself.

All I did so far:
1. Downloaded quasar daemon source from github `Download ZIP`
2. `make pull PLATFORM=linux-x64` - since I'm running 64bit ubuntu
3. `export GOPATH="/home/my_name/go"` - since ~/go would make the next steps impossible
4. `go get -d github.com/scakemyer/quasar` - at first this resulted in segmentation fault, but reinstalling gccgo after that error and re-runing the command kinda worked o.O
5. `go get github.com/mattn/go-isatty`
6. Copied what was downloaded to `/home/my_name/go` to `/src`
7. In terminal I try `make libs` but it results in this error:

```
make[3]: Entering directory `/src/github.com/scakemyer/libtorrent-go'
docker run --rm -v :/go -v /src/github.com/scakemyer/libtorrent-go:/go/src/github.com/scakemyer/libtorrent-go -w /go/src/github.com/scakemyer/libtorrent-go -e GOPATH=/go libtorrent-go:android-arm make re;
Unable to find image 'libtorrent-go:android-arm' locally
Pulling repository libtorrent-go
FATA[0002] Error: image library/libtorrent-go:android-arm not found 
make[3]: *** [android-arm] Error 1
...
```

It gives the same  error for every platform iteration, I am listing android-arm above as an example.

Could somebody please help me with this?

**Comment by KindKitty** [comment]
Also I don't see any .go file on `.../scakemyer/libtorrent-go/linux-x64`, only a Docker file.

**Comment by scakemyer** [comment]
Look at the `.travis.yml` file to see what the build process is. I don't really have time to document all of this.
