### ISSUE TITLE
Fix loading plugin performance on delay start up

### ISSUE THREAD

**Issue by carlosrpg** [scakemyer/quasar#18]
Please, fix the plugin delay on startup.

I managed to do a troubleshooting myself and the main reason is due a lot of Opening/Closing connections with the Kodi itself.

@ quasar/config/config.go there is a lot of calls for xbmc.GetSetting<Type>() that opens and closes the connection for each call.

Refactoring the quasar/xbmc/jsonrpc.go to allow multiple method calls within a single connection will probably fix this issue

**Comment by scakemyer** [comment]
Fixed in scakemyer/plugin.video.quasar#12
