### ISSUE TITLE
Support Pulsar providers

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/quasar#7]
@i96751414 could it be as simple as adding `script.pulsar.` in xbmc.go? Might be great for the transition, but at the same time I kind of like making the distinction between old and new. What are your thoughts on this?

```
        if strings.HasPrefix(addon.ID, "script.quasar.") {
            list = append(list, NewAddonSearcher(addon.ID))
        }
```

**Comment by i96751414** [comment]
Umm.. It won't work, I think. Providers are using a module called `quasar`, which is provided by plugin.video.quasar (i.e. `from quasar import provider`). See this: https://github.com/scakemyer/plugin.video.quasar/blob/master/addon.xml#L10

Those changes would only work if the user has Pulsar installed, which is not a good idea.

**Comment by scakemyer** [comment]
So true, forgot about that one. Never mind then ;) Onward and forward.
