### ISSUE TITLE
With great multi-file comes great responsibility

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/quasar#8]
Now that multi-file support is in (and working pretty well at that @i96751414), there needs to be a few changes to make it useful, like allowing to search by season or as fallback when an episode isn't found.

Providers will obviously have to make changes, but Quasar also needs to leverage that newfound capability.

We could go a few ways about this, like allowing "season x" to not be flagged as an irrelevant item in [SearchEpisodeLinks](https://github.com/scakemyer/quasar/blob/master/providers/xbmc.go#L217), which works but feels hackish, or we could add proper support for season searching. For that I'd propose making an API change for providers, using our pre-1.0 window for it, and adding a `search_season` method to it. It'd also be easier to use that as a fallback when a specific episode isn't found.

**Comment by ghost** [comment]
Ok please, keep me posted how the providers need to be changed to implement that option

**Comment by ghost** [comment]
BTW, in my providers I do that checking.  I had a lot problem, because Quasar only accept English formats.  S00E00 but, it is not the case in different languages.  I remember that I've asked to add 00x00 use in Spanish.  But, it still is different in Dutch or German.

I think that it will be better if Quasar doesn't do that kind of testing and it leaves for the providers.

**Comment by scakemyer** [comment]
I agree, that part I linked to about Quasar filtering "irrelevant" links is too restrictive, and should be left to providers.

**Comment by scakemyer** [comment]
FYI, all that's needed in providers is to allow for "season x" or things like that, the filtering is all left to you now, and Quasar handles the rest, allowing the user to choose which episode to stream within the season packs.

**Comment by ghost** [comment]
Good, I will do the changes this weekend
